# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='doglocation',
            old_name='coordinate_id',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='doglocation',
            old_name='dog_id',
            new_name='dog',
        ),
        migrations.RenameField(
            model_name='dogstatus',
            old_name='dog_id',
            new_name='dog',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='dog_id',
            new_name='dog',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='locationimg',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lostandfound',
            old_name='dog_id',
            new_name='dog',
        ),
        migrations.RenameField(
            model_name='lostandfound',
            old_name='user_id',
            new_name='user',
        ),
    ]
