# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
