# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20170119_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='bleed',
            new_name='breed',
        ),
    ]
